name: app_resume
description: "Sistema de Resumo Acadêmico com IA"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Essenciais para o funcionamento
  flutter_dotenv: ^5.1.0
  http: ^1.2.2
  shared_preferences: ^2.2.3
  path_provider: ^2.1.5
  
  # Exportação e PDF
  pdf: ^3.11.1
  share_plus: ^10.0.3
  printing: ^5.13.4
  
  # Ícones e Utilitários
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  syncfusion_flutter_pdf: ^27.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env